servers:
  prod:
    ip: "192.168.1.10"
    user: "admin"
    password: "secure_password"
    ssh_key: "~/.ssh/id_rsa"

  staging:
    ip: "192.168.1.11"
    user: "deploy"
    password: "another_secure_pass"